### PR TITLE
Disks now only need autoDelete to be specified True at either

### PR DESCRIPTION
**Pull request by mbookman**
pipeline create or run but not both.
Updated compress, fastqc, and set_vcf_sample_id examples.

### CODE REVIEW

**Comment by pgrosu** [comment]
Looks nice, but just wondering, why have have in the Readme files a persistent disk (`PERSISTENT_HDD`) and not a scratch one (`LOCAL_SSD`) if it will be deleted?

**Comment by deflaux** [comment]
LGTM

**Comment by mbookman** [comment]
Hi Paul - Local SSD is much more expensive than HDD-backed persistent disks.
See: https://cloud.google.com/compute/docs/disks/ for an overview of block storage on Compute Engine.
See: https://cloud.google.com/compute/pricing#disk for pricing details.

**Comment by pgrosu** [comment]
Hi Matt,

Wow, didn't realize Local SSD was so expensive!  So compared to persistent, then the maximum local monthly throughput benefit per GB/sec would be greater by 604.4x reads (453.3/0.75), and 160x writes (240/1.5) for an additional $0.178 ($0.218-$0.04).

I guess based on the first link, when it is mentioned that locally is the most economical option in terms of throughput would be because of this:

| Local Provisioned Space (NVMe) | Persistent Provisioned Space (HDD) | Local/Persistent (rounded to the tens)
| --- | --- | --- |
| Reads/$ = 0.75/$0.04 = 18.75 | 453.3/$0.218 = 2079.358 | 2079.358/18.75  ≈ 110x | 
| Writes/$ = 1.5/$0.04 = 37.5 | 240/$0.218 = 1100.917 | 1100.917/37.5  ≈ 30x |

Thanks,
Paul

**Pull request merged**
