### PR TITLE
When called without arguments, the usage instructions are returned

### PR DESCRIPTION
**Pull request by tomsing1**
Fixed argument check, now returning usage instructions only when no arguments are specified, thus enabling users to modify the polling interval via the second argument.

### CODE REVIEW

**Comment by pgrosu** [comment]
Friendly ping @mbookman :)

**Comment by mbookman** [comment]
LGTM

**Comment by pgrosu** [comment]
Thanks Matt.  Would it be okay if you merged it?

**Comment by pgrosu** [comment]
Many thanks Matt :)  @tomsing1 You should be all set now.

**Pull request merged**
